hashgraph/hedera-wallet-connect

README.md, package-lock.json, package.json
- update readme
- 1.0.0
- package name same as repo name
=> Publish to NPM

.github/workflows/publish.yml, package.json
the previous publish command had a typo
=> update package name and fix typo in publish

.github/workflows/prettier.yml, .github/workflows/publish.yml, package.json
install dependencies before building and publishing
=> install dependencies before running publish command

.github/workflows/publish.yml
Match more closely the publish workflow file of stablecoin studio.
We are looking to set up the publish workflow to npm. If we're not to use github secrets, please advise.
Thanks!
=> match stablecoin studio for set up node

package-lock.json, package.json
This PR fixes publishing to NPM because of this issue - https://github.com/hashgraph/hedera-wallet-connect/actions/runs/9200229283
=> Publish v1.1.1 to npm

package-lock.json, package.json
=> update release version

src/lib/dapp/DAppSigner.ts
Adds a description to the function.
=> add notes to the signTransaction function

.github/CODEOWNERS, .github/workflows/prettier.yml, .github/workflows/publish.yml, .github/workflows/test.yml
Use the new latitude runner group and update codeowners file
Fixes #238
=> CI: Update runners to use new runner group

src/lib/dapp/DAppSigner.ts
Add TransactionRecordQuery type to _parseQueryResponse
Fixes #229
**Checklist**
=> Add TransactionRecord Query

src/lib/dapp/index.ts
This PR adds documentation to the `getSigner` method in `dAppConnector`
Fixes #234
=> Add tsdocs to the getSigner method

.github/workflows/test.yml
Update jest-coverage-report-action to commit ID for v2.3.1. Add Codecov functionality.
**Related Issue(s)**:
Fixes: #215
=> ci: Update hedera-wallet-connect per Q3 audit findings

src/lib/dapp/index.ts
Small change to try / catch disconnecting a session
Fixes #291 
Fixes #281
=> use try catch instead

.github/workflows/test.yml
This PR modifies the GITHUB_TOKEN permissions by adding a write permission for "statuses". It aims to fix the "HttpError: Resource not accessible by integration" error of the unit tests after a PR is merged.
Fixes #
**Checklist**
=> ci: Add statuses write permission

.github/workflows/test.yml
Updating github actions to their step-security maintained version.
Fixes #306 
**Checklist**
=> ci: Updating action to use step-security maintained version.

.github/workflows/test.yml
This PR aims to fix a typo in a prior commit that updates the a github action to a step-security maintained version.
Fixes #306 
**Checklist**
=> ci: Updating action to use step-security maintained version + fixing a typo.

.github/workflows/test.yml
This PR aims to roll-back codecov upload action to an older more stable version. Once issues are resolved in latest version we can re-update.
Fixes #364 
**Checklist**
=> ci: Roll-back of codecov version due to issues with latest one. #395

.github/CODEOWNERS
Update CODEOWNERS to provide maintainers ownership of all files in their repos
Fixes #374 
N/A
**Checklist**
=> chore: add repo maintainers in the CODEOWNERS file

docs/docs/installation.md
This PR adds instructions for react-native in the README.
This should close #376
=> React Native instructions

docs/docs/hedera-integration.md
this PR updates the Hedera Integration documentation page to factor in various community feedback
=> Update Hedera Integration Pathways

jest.config.ts, test/dapp/DAppSigner.test.ts, test/dapp/index.test.ts, test/setup.ts, test/wallet/methods/wallet-executeTransaction.test.ts, test/wallet/methods/wallet-getNodeAddresses.test.ts, test/wallet/methods/wallet-signAndExecuteQuery.test.ts, test/wallet/methods/wallet-signAndExecuteTransaction.test.ts, test/wallet/methods/wallet-signMessage.test.ts, test/wallet/methods/wallet-signTransaction.test.ts
This PR fixed tests and removed console warnings/errors logs in the [`introduce-v2`](https://github.com/hashgraph/hedera-wallet-connect/tree/introduce-v2) branch.
**Checklist**
=> Fixed tests in introduce-v2 branch

.github/workflows/publish-canary.yml, .github/workflows/test.yml
Updated workflow files for v2 for easier review.
For reference - https://github.com/hashgraph/hedera-wallet-connect/pull/504#pullrequestreview-2874704603
=> update .github workflow files for smaller PR review
